name: CI

on:
  push:
    branches: [develop, main]
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v6
      - uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm prisma generate
        env:
          DATABASE_URL: postgresql://unused:unused@localhost/unused
      - name: Check formatting
        run: pnpm prettier:check
      - name: Check linting
        run: pnpm lint:check

  build:
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v6
      - uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm prisma generate
        env:
          DATABASE_URL: postgresql://unused:unused@localhost/unused
      - name: Run build
        run: pnpm next build
        env:
          DATABASE_URL: postgresql://unused:unused@localhost/unused
